apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-scaled-service
  labels:
    app: helloworld-openshift-safe
  namespace: openshift-devspaces
spec:
  # The name MUST connect with the scaleTargetRef reference in the ScaledObject.
  replicas: 0 
  selector:
    matchLabels:
      app: helloworld-openshift-safe
  template:
    metadata:
      labels:
        app: helloworld-openshift-safe
    spec:
      containers:
      - name: helloworld-safe-container
        image: openshift/hello-openshift
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"